# Generated by Django 5.0.6 on 2024-07-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="color",
            field=models.CharField(default="#a8a8a8", max_length=7),
        ),
    ]
