# Generated by Django 5.0.6 on 2024-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
